spring:
  application:
    name: WakeThemAllBot
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${BD_USERNAME:admin}
    password: ${BD_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
logging:
  level:
    root: INFO
server:
  port: ${PORT:8080}

app:
  webhook-url: ${WEBHOOK_URL}